#!/usr/bin/env node

/**
 * Post-build script to generate Angular Material-style individual component bundles.
 * This runs after ng-packagr builds the main library.
 */

const fs = require('fs').promises;
const path = require('path');

// Component information (this would be generated by Stencil)
const COMPONENTS = [
  { tagName: 'my-component' },
  { tagName: 'my-counter' },
  { tagName: 'my-button' },
  { tagName: 'my-checkbox' },
  { tagName: 'my-input' },
  { tagName: 'my-radio' },
  { tagName: 'my-radio-group' },
  // Add more components as needed
];

const DIST_DIR = path.resolve(__dirname, '../projects/library/dist');

/**
 * Generates individual component directories with type definitions.
 */
async function generateComponentDirectories() {
  console.log('Generating individual component directories...');
  
  for (const component of COMPONENTS) {
    const componentDir = path.join(DIST_DIR, component.tagName);
    const indexPath = path.join(componentDir, 'index.d.ts');
    
    // Create component directory
    await fs.mkdir(componentDir, { recursive: true });
    
    // Generate type definitions
    const tagNameAsPascal = toPascalCase(component.tagName);
    const content = [
      '/*',
      ` * Individual component types for ${component.tagName}`,
      ' * Enables tree-shaking by allowing imports like:',
      ` * import { ${tagNameAsPascal} } from 'component-library-angular/${component.tagName}';`,
      ' */',
      '',
      `export { ${tagNameAsPascal} } from '../index';`,
      '',
    ].join('\n');
    
    await fs.writeFile(indexPath, content);
    console.log(`✓ Generated ${component.tagName}/index.d.ts`);
  }
}

/**
 * Updates package.json with individual component exports.
 */
async function updatePackageJsonExports() {
  console.log('Updating package.json exports...');
  
  const packageJsonPath = path.join(DIST_DIR, 'package.json');
  
  try {
    // Read existing package.json
    const packageJsonContent = await fs.readFile(packageJsonPath, 'utf8');
    const packageJson = JSON.parse(packageJsonContent);
    
    // Add individual component exports
    if (!packageJson.exports) {
      packageJson.exports = {};
    }
    
    // Add exports for each component
    COMPONENTS.forEach((component) => {
      packageJson.exports[`./${component.tagName}`] = {
        types: `./${component.tagName}/index.d.ts`,
        default: `./fesm2022/${component.tagName}.mjs`
      };
    });
    
    // Write updated package.json
    const updatedContent = JSON.stringify(packageJson, null, 2) + '\n';
    await fs.writeFile(packageJsonPath, updatedContent);
    
    console.log('✓ Updated package.json exports');
  } catch (error) {
    console.error('Failed to update package.json:', error);
    process.exit(1);
  }
}

/**
 * Creates individual FESM bundles for each component.
 * For now, these will be simple re-exports from the main bundle.
 */
async function createIndividualBundles() {
  console.log('Creating individual FESM bundles...');
  
  const fesmDir = path.join(DIST_DIR, 'fesm2022');
  await fs.mkdir(fesmDir, { recursive: true });
  
  for (const component of COMPONENTS) {
    const bundlePath = path.join(fesmDir, `${component.tagName}.mjs`);
    const tagNameAsPascal = toPascalCase(component.tagName);
    
    // Simple re-export from main bundle
    const content = [
      `// Individual bundle for ${component.tagName}`,
      `export { ${tagNameAsPascal} } from './component-library-angular.mjs';`,
      '',
    ].join('\n');
    
    await fs.writeFile(bundlePath, content);
    console.log(`✓ Generated fesm2022/${component.tagName}.mjs`);
  }
}

/**
 * Converts kebab-case to PascalCase.
 */
function toPascalCase(str) {
  return str
    .split('-')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join('');
}

/**
 * Main execution function.
 */
async function main() {
  try {
    console.log('🚀 Starting post-build process for Angular Material-style bundles...');
    
    await generateComponentDirectories();
    await createIndividualBundles();
    await updatePackageJsonExports();
    
    console.log('✅ Post-build process completed successfully!');
    console.log('');
    console.log('Individual component imports are now available:');
    COMPONENTS.forEach((component) => {
      const pascalName = toPascalCase(component.tagName);
      console.log(`  import { ${pascalName} } from 'component-library-angular/${component.tagName}';`);
    });
  } catch (error) {
    console.error('❌ Post-build process failed:', error);
    process.exit(1);
  }
}

main();
